# ===========================
# DB
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/bws-apigen-db
spring.datasource.username=${POSTGRES_PROD_USERNAME}
spring.datasource.password=${POSTGRES_PROD_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# STRIPE
# ===========================
stripe.secret=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.apigen.price-id.admin=${STRIPE_APIGEN_PRICE_ID_ADMIN}
stripe.apigen.price-id.solo=${STRIPE_APIGEN_PRICE_ID_SOLO}
stripe.apigen.price-id.small=${STRIPE_APIGEN_PRICE_ID_SMALL}
stripe.apigen.price-id.full=${STRIPE_APIGEN_PRICE_ID_FULL}

jwt.secret=${JWT_SECRET_KEY}