spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ===========================
# STRIPE
# ===========================
stripe.secret=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.apigen.price-id.admin=${STRIPE_APIGEN_PRICE_ID_ADMIN}
stripe.apigen.price-id.solo=${STRIPE_APIGEN_PRICE_ID_SOLO}
stripe.apigen.price-id.small=${STRIPE_APIGEN_PRICE_ID_SMALL}
stripe.apigen.price-id.full=${STRIPE_APIGEN_PRICE_ID_FULL}

jwt.secret=${JWT_SECRET_KEY}